; Generated by gen_battle.py -- do not edit.
; Standalone unit; see the note in worlddata.asm.
.include "hdr.asm"

.section ".rodata_bg_night" superfree
bg_night_pic: .incbin "assets/bg_night.pic"
bg_night_map: .incbin "assets/bg_night.map"
bg_night_pal: .incbin "assets/bg_night.pal"
.ends

.section ".rodata_bg_forest" superfree
bg_forest_pic: .incbin "assets/bg_forest.pic"
bg_forest_map: .incbin "assets/bg_forest.map"
bg_forest_pal: .incbin "assets/bg_forest.pal"
.ends

.section ".rodata_bg_shore" superfree
bg_shore_pic: .incbin "assets/bg_shore.pic"
bg_shore_map: .incbin "assets/bg_shore.map"
bg_shore_pal: .incbin "assets/bg_shore.pal"
.ends

.section ".rodata_bg_salt" superfree
bg_salt_pic: .incbin "assets/bg_salt.pic"
bg_salt_map: .incbin "assets/bg_salt.map"
bg_salt_pal: .incbin "assets/bg_salt.pal"
.ends

.section ".rodata_bg_iron" superfree
bg_iron_pic: .incbin "assets/bg_iron.pic"
bg_iron_map: .incbin "assets/bg_iron.map"
bg_iron_pal: .incbin "assets/bg_iron.pal"
.ends

.section ".rodata_bg_void" superfree
bg_void_pic: .incbin "assets/bg_void.pic"
bg_void_map: .incbin "assets/bg_void.map"
bg_void_pal: .incbin "assets/bg_void.pal"
.ends

.section ".rodata_bg_dawn" superfree
bg_dawn_pal: .incbin "assets/bg_dawn.pal"
.ends
