#!/usr/bin/env python3
"""H-DMA tables: per-scanline colour gradients and horizontal scroll bands.

Two things a 16-colour backdrop cannot do on its own:

  sky_*.tbl   a per-line subtract level written to $2132 COLDATA. The palette
              holds the *brightest* version of the sky and the raster darkens
              it toward the top and the bottom, which buys a gradient far
              smoother than four dithered bands and a vignette for free.

  wave*.tbl   a per-line value for $210D BG1HOFS. Eight phase variants; the
              game advances which one channel 2 reads, so the water ripples
              and the salt shimmers without touching a byte of the table.

---- table format ----------------------------------------------------------

cpu-system.md, H-DMA table formats. A direct (Type 0) table is a sequence of
{count, data...} blocks terminated by a zero count. With bit 7 of the count
set, the block is "repeat" mode: each of the next (count & 0x7F) lines gets its
own data. That is what a per-line gradient wants, and the count is 7 bits, so
224 lines is two blocks of 112.

$2132 takes one byte a line (write mode 000). $210D is a write-twice register,
so it takes two (write mode 010, low byte then high) -- which is also why the
scroll tables are twice the size.
"""
import math
import struct

import snesgfx as g

LINES = 224
BLOCK = 112


def repeat_table(values, stride):
    """values: LINES entries, each already `stride` bytes."""
    out = bytearray()
    for start in (0, BLOCK):
        out.append(0x80 | BLOCK)
        for i in range(start, start + BLOCK):
            out += values[i]
    out.append(0x00)
    return bytes(out)


def coldata(level):
    """$2132: bits 7-5 select the red, green and blue channels; bits 4-0 are
    the level. $E0 sets all three at once, so the subtract stays neutral."""
    return bytes([0xE0 | max(0, min(31, int(level)))])


def sky(horizon, top, floor_amt, band=0.0):
    """Darken toward the top of the sky and, gently, toward the bottom of the
    floor. `band` adds a soft halo just above the horizon."""
    vals = []
    for y in range(LINES):
        if y < horizon:
            t = 1.0 - (y / float(horizon))          # 1 at the top, 0 at horizon
            v = top * (t ** 1.4)
            if band:
                d = abs(y - (horizon - 10)) / 14.0
                v -= band * max(0.0, 1.0 - d)
        else:
            t = (y - horizon) / float(LINES - horizon)
            v = floor_amt * (t ** 1.8)
        vals.append(coldata(v))
    return repeat_table(vals, 1)


def wave(phase, amp, period, taper_from=0, drift=0.0):
    """A per-line horizontal offset. taper_from is the line above which the
    offset is zero, so only the water moves and not the sky above it."""
    vals = []
    for y in range(LINES):
        if y < taper_from:
            v = 0
        else:
            t = (y - taper_from) / float(max(1, LINES - taper_from))
            v = amp * t * math.sin(y * period + phase) + drift * t
        n = int(round(v)) & 0x03FF
        vals.append(struct.pack('<H', n))
    return repeat_table(vals, 2)


# One sky per backdrop, matching gen_battle.py's REGIONS order.
SKIES = [
    ('night',  dict(horizon=108, top=14, floor_amt=8,  band=3)),
    ('forest', dict(horizon=120, top=18, floor_amt=10, band=0)),
    ('shore',  dict(horizon=96,  top=12, floor_amt=6,  band=4)),
    ('salt',   dict(horizon=104, top=10, floor_amt=5,  band=2)),
    ('iron',   dict(horizon=96,  top=16, floor_amt=12, band=0)),
    ('void',   dict(horizon=150, top=20, floor_amt=16, band=0)),
]

# The field is top-down, so it gets a plain vignette rather than a sky.
# Gentle: the field is lit by the same moon everywhere and a strong
# vignette on a top-down map reads as a bug rather than as depth.
FIELD_SKY = dict(horizon=112, top=5, floor_amt=4, band=0)

WAVE_PHASES = 8


def generate_hdma():
    total = 0
    for name, kw in SKIES:
        total += g.write('sky_%s.tbl' % name, sky(**kw))
    total += g.write('sky_field.tbl', sky(**FIELD_SKY))

    for i in range(WAVE_PHASES):
        ph = i * (2 * math.pi / WAVE_PHASES)
        total += g.write('wave%d.tbl' % i,
                         wave(ph, amp=3.2, period=0.16, taper_from=96))

    with open('hdmadata.asm', 'w') as f:
        f.write("; Generated by gen_hdma.py -- do not edit.\n"
                "; Standalone unit; see the note in worlddata.asm.\n"
                '.include "hdr.asm"\n\n'
                "; H-DMA reads these with the DMA controller, not the CPU, and a\n"
                "; channel's A-bus address does not carry into the bank byte --\n"
                "; so a table that straddled a bank boundary would walk off the\n"
                "; end of the bank mid-frame. `superfree` places a section inside\n"
                "; one bank, which is exactly that guarantee.\n"
                '.section ".rodata_hdma" superfree\n')
        for name, _ in SKIES:
            f.write('sky_%s_tbl: .incbin "%s"\n'
                    % (name, g.asset('sky_%s.tbl' % name)))
        f.write('sky_field_tbl: .incbin "%s"\n' % g.asset('sky_field.tbl'))
        for i in range(WAVE_PHASES):
            f.write('wave%d_tbl: .incbin "%s"\n' % (i, g.asset('wave%d.tbl' % i)))
        f.write('.ends\n')

    with open('src/hdmamap.h', 'w') as f:
        f.write("/* Generated by gen_hdma.py -- do not edit. */\n"
                "#ifndef HDMAMAP_H\n#define HDMAMAP_H\n\n")
        f.write("#define WAVE_PHASES %d\n\n" % WAVE_PHASES)
        for name, _ in SKIES:
            f.write("extern char sky_%s_tbl;\n" % name)
        f.write("extern char sky_field_tbl;\n")
        for i in range(WAVE_PHASES):
            f.write("extern char wave%d_tbl;\n" % i)
        f.write("\nstatic u8 *skyTable(u8 n) {\n    switch (n) {\n")
        for i, (name, _) in enumerate(SKIES[:-1]):
            f.write("    case %d:\n        return (u8 *)&sky_%s_tbl;\n" % (i, name))
        f.write("    default:\n        return (u8 *)&sky_%s_tbl;\n"
                % SKIES[-1][0])
        f.write("    }\n}\n\n")
        f.write("static u8 *waveTable(u8 n) {\n    switch (n & 7) {\n")
        for i in range(WAVE_PHASES - 1):
            f.write("    case %d:\n        return (u8 *)&wave%d_tbl;\n" % (i, i))
        f.write("    default:\n        return (u8 *)&wave%d_tbl;\n"
                % (WAVE_PHASES - 1))
        f.write("    }\n}\n\n#endif\n")

    print("hdma: %d bytes (%d skies, %d wave phases)"
          % (total, len(SKIES) + 1, WAVE_PHASES))


if __name__ == '__main__':
    generate_hdma()
