; Generated by gen_hdma.py -- do not edit.
; Standalone unit; see the note in worlddata.asm.
.include "hdr.asm"

; H-DMA reads these with the DMA controller, not the CPU, and a
; channel's A-bus address does not carry into the bank byte --
; so a table that straddled a bank boundary would walk off the
; end of the bank mid-frame. `superfree` places a section inside
; one bank, which is exactly that guarantee.
.section ".rodata_hdma" superfree
sky_night_tbl: .incbin "assets/sky_night.tbl"
sky_forest_tbl: .incbin "assets/sky_forest.tbl"
sky_shore_tbl: .incbin "assets/sky_shore.tbl"
sky_salt_tbl: .incbin "assets/sky_salt.tbl"
sky_iron_tbl: .incbin "assets/sky_iron.tbl"
sky_void_tbl: .incbin "assets/sky_void.tbl"
sky_field_tbl: .incbin "assets/sky_field.tbl"
wave0_tbl: .incbin "assets/wave0.tbl"
wave1_tbl: .incbin "assets/wave1.tbl"
wave2_tbl: .incbin "assets/wave2.tbl"
wave3_tbl: .incbin "assets/wave3.tbl"
wave4_tbl: .incbin "assets/wave4.tbl"
wave5_tbl: .incbin "assets/wave5.tbl"
wave6_tbl: .incbin "assets/wave6.tbl"
wave7_tbl: .incbin "assets/wave7.tbl"
.ends
