; Generated by gen_hdma.py -- do not edit.
; Standalone unit; see the note in worlddata.asm.
.include "hdr.asm"

; H-DMA reads these with the DMA controller, not the CPU, and a
; channel's A-bus address does not carry into the bank byte --
; so a table that straddled a bank boundary would walk off the
; end of the bank mid-frame. `superfree` places a section inside
; one bank, which is exactly that guarantee.
.section ".rodata_hdma" superfree
sky_night_tbl: .incbin "sky_night.tbl"
sky_forest_tbl: .incbin "sky_forest.tbl"
sky_shore_tbl: .incbin "sky_shore.tbl"
sky_salt_tbl: .incbin "sky_salt.tbl"
sky_iron_tbl: .incbin "sky_iron.tbl"
sky_void_tbl: .incbin "sky_void.tbl"
sky_field_tbl: .incbin "sky_field.tbl"
wave0_tbl: .incbin "wave0.tbl"
wave1_tbl: .incbin "wave1.tbl"
wave2_tbl: .incbin "wave2.tbl"
wave3_tbl: .incbin "wave3.tbl"
wave4_tbl: .incbin "wave4.tbl"
wave5_tbl: .incbin "wave5.tbl"
wave6_tbl: .incbin "wave6.tbl"
wave7_tbl: .incbin "wave7.tbl"
.ends
