; Generated by gen_world.py -- do not edit.
;
; A standalone unit, not an .include: snes_rules globs every
; root *.asm into OFILES, so a file that is also included
; from data.asm would have its labels linked twice.
.include "hdr.asm"
;
; One section per region: a tileset and a tilemap are 8KB each
; and a WLA section cannot straddle a bank boundary in 32KB
; LoROM, so they are kept apart region by region.

.section ".rodata_village" superfree
area_village_pic: .incbin "assets/area_village.pic"
area_village_map: .incbin "assets/area_village.map"
area_village_col: .incbin "assets/area_village.col"
area_village_pal: .incbin "assets/area_village.pal"
area_village_anm: .incbin "assets/area_village.anm"
.ends

.section ".rodata_fields" superfree
area_fields_pic: .incbin "assets/area_fields.pic"
area_fields_map: .incbin "assets/area_fields.map"
area_fields_col: .incbin "assets/area_fields.col"
area_fields_pal: .incbin "assets/area_fields.pal"
area_fields_anm: .incbin "assets/area_fields.anm"
.ends

.section ".rodata_forest" superfree
area_forest_pic: .incbin "assets/area_forest.pic"
area_forest_map: .incbin "assets/area_forest.map"
area_forest_col: .incbin "assets/area_forest.col"
area_forest_pal: .incbin "assets/area_forest.pal"
area_forest_anm: .incbin "assets/area_forest.anm"
.ends

.section ".rodata_shore" superfree
area_shore_pic: .incbin "assets/area_shore.pic"
area_shore_map: .incbin "assets/area_shore.map"
area_shore_col: .incbin "assets/area_shore.col"
area_shore_pal: .incbin "assets/area_shore.pal"
area_shore_anm: .incbin "assets/area_shore.anm"
.ends

.section ".rodata_salt" superfree
area_salt_pic: .incbin "assets/area_salt.pic"
area_salt_map: .incbin "assets/area_salt.map"
area_salt_col: .incbin "assets/area_salt.col"
area_salt_pal: .incbin "assets/area_salt.pal"
area_salt_anm: .incbin "assets/area_salt.anm"
.ends

.section ".rodata_fortress" superfree
area_fortress_pic: .incbin "assets/area_fortress.pic"
area_fortress_map: .incbin "assets/area_fortress.map"
area_fortress_col: .incbin "assets/area_fortress.col"
area_fortress_pal: .incbin "assets/area_fortress.pal"
area_fortress_anm: .incbin "assets/area_fortress.anm"
.ends

.section ".rodata_hush" superfree
area_hush_pic: .incbin "assets/area_hush.pic"
area_hush_map: .incbin "assets/area_hush.map"
area_hush_col: .incbin "assets/area_hush.col"
area_hush_pal: .incbin "assets/area_hush.pal"
area_hush_anm: .incbin "assets/area_hush.anm"
.ends
