/* Generated by gen_music.py -- do not edit.
 *
 * Order ranges of the themes inside res/ttbgm.it. The game
 * keeps one looping by watching spcGetMusicPosition() and
 * re-issuing spcPlay when the position leaves the range.
 * Every order plays the pattern of the same number, so these
 * hold whether that call reports an order or a pattern. */
#ifndef TT_MUSIC_H
#define TT_MUSIC_H

#define MUS_TOWN_FIRST 0
#define MUS_TOWN_LAST  2
#define MUS_FIELD_FIRST 3
#define MUS_FIELD_LAST  6
#define MUS_FOREST_FIRST 7
#define MUS_FOREST_LAST  9
#define MUS_SHORE_FIRST 10
#define MUS_SHORE_LAST  12
#define MUS_SALT_FIRST 13
#define MUS_SALT_LAST  15
#define MUS_FORTRESS_FIRST 16
#define MUS_FORTRESS_LAST  19
#define MUS_HUSH_FIRST 20
#define MUS_HUSH_LAST  21
#define MUS_BATTLE_FIRST 22
#define MUS_BATTLE_LAST  25
#define MUS_BOSS_FIRST 26
#define MUS_BOSS_LAST  29
#define MUS_FINAL_FIRST 30
#define MUS_FINAL_LAST  33
#define MUS_FANFARE_FIRST 34
#define MUS_FANFARE_LAST  34
#define MUS_TITLE_FIRST 35
#define MUS_TITLE_LAST  36
#define MUS_ENDING_FIRST 37
#define MUS_ENDING_LAST  39

#endif
