/* Generated by gen_battle.py -- do not edit. */
#ifndef BGMAP_H
#define BGMAP_H

#define BACKDROP_COUNT 6

extern char bg_night_pic, bg_night_map, bg_night_pal;
extern char bg_forest_pic, bg_forest_map, bg_forest_pal;
extern char bg_shore_pic, bg_shore_map, bg_shore_pal;
extern char bg_salt_pic, bg_salt_map, bg_salt_pal;
extern char bg_iron_pic, bg_iron_map, bg_iron_pal;
extern char bg_void_pic, bg_void_map, bg_void_pal;
extern char bg_dawn_pal;

static u8 *backdropPic(u8 n) {
    switch (n) {
    case 0:
        return (u8 *)&bg_night_pic;
    case 1:
        return (u8 *)&bg_forest_pic;
    case 2:
        return (u8 *)&bg_shore_pic;
    case 3:
        return (u8 *)&bg_salt_pic;
    case 4:
        return (u8 *)&bg_iron_pic;
    default:
        return (u8 *)&bg_void_pic;
    }
}

static u8 *backdropMap(u8 n) {
    switch (n) {
    case 0:
        return (u8 *)&bg_night_map;
    case 1:
        return (u8 *)&bg_forest_map;
    case 2:
        return (u8 *)&bg_shore_map;
    case 3:
        return (u8 *)&bg_salt_map;
    case 4:
        return (u8 *)&bg_iron_map;
    default:
        return (u8 *)&bg_void_map;
    }
}

static u8 *backdropPal(u8 n) {
    switch (n) {
    case 0:
        return (u8 *)&bg_night_pal;
    case 1:
        return (u8 *)&bg_forest_pal;
    case 2:
        return (u8 *)&bg_shore_pal;
    case 3:
        return (u8 *)&bg_salt_pal;
    case 4:
        return (u8 *)&bg_iron_pal;
    default:
        return (u8 *)&bg_void_pal;
    }
}

#endif
