/* Generated by gen_font.py -- do not edit.
 * Tile indices into the BG2 character sheet at $2000. */
#ifndef GFXMAP_H
#define GFXMAP_H

#define WIN_TL   0xE0
#define WIN_T    0xE1
#define WIN_TR   0xE2
#define WIN_BL   0xE3
#define WIN_B    0xE4
#define WIN_BR   0xE5
#define WIN_L0   0xE6
#define WIN_R0   0xEC
#define WIN_F0   0xF2
#define WIN_BLACK 0xF8
#define GRAD_STEPS 6

#define ICON_CURSOR   0x60
#define ICON_SLEEP    0x61
#define ICON_DEAD     0x62
#define ICON_POISON   0x63
#define ICON_HASTE    0x64
#define ICON_SLOW     0x65
#define ICON_MP       0x66
#define ICON_DRUM     0x67

#define GAUGE0   0xC0

/* Title logo: bigLetterTile(c) gives the top-left character
 * of a 16x16 letter; +1 is its right half and +0x10 the row
 * below. Returns 0xFF for a character with no big form. */
#define BIG_BASE 0x70
#define BIG_LETTERS "TUNGSAHR"

#endif
