/* Generated by gen_hdma.py -- do not edit. */
#ifndef HDMAMAP_H
#define HDMAMAP_H

#define WAVE_PHASES 8

extern char sky_night_tbl;
extern char sky_forest_tbl;
extern char sky_shore_tbl;
extern char sky_salt_tbl;
extern char sky_iron_tbl;
extern char sky_void_tbl;
extern char sky_field_tbl;
extern char wave0_tbl;
extern char wave1_tbl;
extern char wave2_tbl;
extern char wave3_tbl;
extern char wave4_tbl;
extern char wave5_tbl;
extern char wave6_tbl;
extern char wave7_tbl;

static u8 *skyTable(u8 n) {
    switch (n) {
    case 0:
        return (u8 *)&sky_night_tbl;
    case 1:
        return (u8 *)&sky_forest_tbl;
    case 2:
        return (u8 *)&sky_shore_tbl;
    case 3:
        return (u8 *)&sky_salt_tbl;
    case 4:
        return (u8 *)&sky_iron_tbl;
    default:
        return (u8 *)&sky_void_tbl;
    }
}

static u8 *waveTable(u8 n) {
    switch (n & 7) {
    case 0:
        return (u8 *)&wave0_tbl;
    case 1:
        return (u8 *)&wave1_tbl;
    case 2:
        return (u8 *)&wave2_tbl;
    case 3:
        return (u8 *)&wave3_tbl;
    case 4:
        return (u8 *)&wave4_tbl;
    case 5:
        return (u8 *)&wave5_tbl;
    case 6:
        return (u8 *)&wave6_tbl;
    default:
        return (u8 *)&wave7_tbl;
    }
}

#endif
