/* Generated by gen_sprites.py -- do not edit.
 * OBJ character names into the resident sheet at VRAM $0000,
 * and offsets into the streamed enemy blob. */
#ifndef SPRMAP_H
#define SPRMAP_H

#define SPR_WALK      0   /* +i*2: down/up/left/right x2 */
#define SPR_TUNG      32
#define SPR_TUNG_ATK  36
#define SPR_PATAPIM   40
#define SPR_PATAPIM_ATK  44
#define SPR_TRALA     96
#define SPR_TRALA_ATK 100
#define SPR_LIRILI   104
#define SPR_LIRILI_ATK 108
#define SPR_BOMBARD  160
#define SPR_BOMBARD_ATK 164
/* OBJ palette slots. CGRAM 128 upward, sixteen colours each. */
#define P_TUNG    0
#define P_TRALA   1
#define P_LIRILI  2
#define P_ENEMY   3
#define P_BOSS    4
#define P_PATAPIM 5
#define P_FX      6
#define P_ENEMY2  7

#define OPAL_TUNG   P_TUNG
#define OPAL_ENEMY  P_ENEMY
#define OPAL_BOSS   P_BOSS

/* Battle sprite name per party member, idle then acting. */
static const u16 sprPartyName[10] = {
    32, 36, 40, 44, 96, 100, 104, 108, 160, 164
};
static const u8 sprPartyPal[5] = {
    P_TUNG, P_PATAPIM, P_TRALA, P_LIRILI, P_BOSS
};

/* Dialogue portraits. 32x32, one large OBJ in the field's
 * 16/32 size pair, streamed into the scratch page at a block
 * the enemy art never reaches. */
#define FACE_NONE 0
#define FACE_TUNG       1
#define FACE_NONNA      2
#define FACE_PATAPIM    3
#define FACE_TRALA      4
#define FACE_LIRILI     5
#define FACE_BOMBARD    6
#define FACE_SILENZIO   7
#define FACE_CAPPUCCINA 8
#define FACE_COUNT 9

/* Indexed by FACE_* - 1. */
static const u8 facePal[8] = {
    P_TUNG, P_TUNG, P_PATAPIM, P_TRALA, P_LIRILI, P_BOSS, P_ENEMY, P_TUNG
};

/* Byte offset of each design inside enemies.pic. The blob is
 * one section and therefore one bank, so base + offset never
 * needs 24-bit arithmetic. */
static const u16 enemyArtOffset[25] = {
        0,     0,   512,  1024,  1536,  2048,
     2560,  3072,  3584,  4096,  4608,  5120,
     5632,  6144,  8192, 10240, 12288, 14336,
    16384, 18432, 18944, 19456, 19968, 20480,
    20992,
};

static const u8 enemyPal[25] = {
    P_ENEMY, P_ENEMY, P_ENEMY, P_ENEMY, P_ENEMY, P_ENEMY, P_PATAPIM, P_TRALA, P_ENEMY, P_ENEMY2, P_ENEMY2, P_ENEMY, P_ENEMY, P_PATAPIM, P_TRALA, P_ENEMY, P_BOSS, P_ENEMY, P_ENEMY, P_ENEMY2, P_ENEMY2, P_PATAPIM, P_TRALA, P_LIRILI, P_ENEMY
};

#endif
