/* Generated by gen_title.py -- do not edit. */
#ifndef TITLEMAP_H
#define TITLEMAP_H

/* The two runs of CGRAM entries the title rotates. Rotating
 * the logo ramp walks the shine down the letters; rotating
 * the star ramp makes the field twinkle. Both are a handful
 * of $2122 writes and no tile is ever touched. */
#define TITLE_LOGO0 12
#define TITLE_LOGO_N 4
#define TITLE_STAR0 3
#define TITLE_STAR_N 3

static const u16 titleLogoRamp[4] = {
    0x0D2E, 0x1617, 0x333E, 0x63DF
};

static const u16 titleStarRamp[3] = {
    0x498C, 0x6AB5, 0x7FFF
};

#endif
