/* Generated by gen_title.py -- do not edit. */
#ifndef TITLEMAP_H
#define TITLEMAP_H

/* The title animates by palette alone: TITLE_FRAMES blocks of
 * BG palettes 2-7, one uploaded every TITLE_STEP frames. The
 * light circling the logo and the twinkling stars are in the
 * colours; no character is ever rewritten. */
#define TITLE_FRAMES 8
#define TITLE_STEP 5
#define TITLE_PAL_BYTES 192
#define TITLE_PIC_BYTES 16384

#endif
