/* Generated by gen_world.py -- do not edit. */
#ifndef WORLDMAP_H
#define WORLDMAP_H

#define MAP_W 32
#define MAP_H 32

#define COL_BLOCK 0x01
#define COL_ENC   0x02
#define COL_TRIG  0x04
#define COL_EVENT(c) ((c) >> 4)

#define AREA_VILLAGE   0
#define AREA_FIELDS    1
#define AREA_FOREST    2
#define AREA_SHORE     3
#define AREA_SALT      4
#define AREA_FORTRESS  5
#define AREA_HUSH      6
#define AREA_COUNT     7

#define EV_EXIT1  1
#define EV_EXIT2  2
#define EV_EXIT3  3
#define EV_EXIT4  4
#define EV_TALK1  5
#define EV_TALK2  6
#define EV_TALK3  7
#define EV_TALK4  8
#define EV_INN    9
#define EV_SHOP   10
#define EV_SAVE   11
#define EV_BOSS   12
#define EV_STORY  13

#define SPAWN_AREA AREA_VILLAGE
#define SPAWN_X 16
#define SPAWN_Y 20

/* Exit id 1-4 of area a is at index a * 4 + (id - 1). */
static const u8 areaExitTo[AREA_COUNT * 4] = {
      1, 255, 255, 255,   0,   2, 255, 255,
      1,   3, 255, 255,   2,   4, 255, 255,
      3,   5, 255, 255,   4,   6, 255, 255,
      5, 255, 255, 255,
};

static const u8 areaExitX[AREA_COUNT * 4] = {
      2,   0,   0,   0,  29,   2,   0,   0,
     29,   2,   0,   0,  29,   2,   0,   0,
     25,   4,   0,   0,  27,   6,   0,   0,
     27,   0,   0,   0,
};

static const u8 areaExitY[AREA_COUNT * 4] = {
     13,   0,   0,   0,  15,  17,   0,   0,
     13,   9,   0,   0,  17,  22,   0,   0,
      2,  28,   0,   0,   4,  27,   0,   0,
      8,   0,   0,   0,
};

/* Region assets. Defined in worlddata.asm, which this file
 * also generates, so a region cannot exist in one and not the
 * other. */
extern char area_village_pic;
extern char area_village_map;
extern char area_village_col;
extern char area_village_pal;
extern char area_village_anm;
extern char area_fields_pic;
extern char area_fields_map;
extern char area_fields_col;
extern char area_fields_pal;
extern char area_fields_anm;
extern char area_forest_pic;
extern char area_forest_map;
extern char area_forest_col;
extern char area_forest_pal;
extern char area_forest_anm;
extern char area_shore_pic;
extern char area_shore_map;
extern char area_shore_col;
extern char area_shore_pal;
extern char area_shore_anm;
extern char area_salt_pic;
extern char area_salt_map;
extern char area_salt_col;
extern char area_salt_pal;
extern char area_salt_anm;
extern char area_fortress_pic;
extern char area_fortress_map;
extern char area_fortress_col;
extern char area_fortress_pal;
extern char area_fortress_anm;
extern char area_hush_pic;
extern char area_hush_map;
extern char area_hush_col;
extern char area_hush_pal;
extern char area_hush_anm;

static u8 *areaPic(u8 a) {
    switch (a) {
    case AREA_VILLAGE:
        return (u8 *)&area_village_pic;
    case AREA_FIELDS:
        return (u8 *)&area_fields_pic;
    case AREA_FOREST:
        return (u8 *)&area_forest_pic;
    case AREA_SHORE:
        return (u8 *)&area_shore_pic;
    case AREA_SALT:
        return (u8 *)&area_salt_pic;
    case AREA_FORTRESS:
        return (u8 *)&area_fortress_pic;
    default:
        return (u8 *)&area_hush_pic;
    }
}

static u8 *areaMap(u8 a) {
    switch (a) {
    case AREA_VILLAGE:
        return (u8 *)&area_village_map;
    case AREA_FIELDS:
        return (u8 *)&area_fields_map;
    case AREA_FOREST:
        return (u8 *)&area_forest_map;
    case AREA_SHORE:
        return (u8 *)&area_shore_map;
    case AREA_SALT:
        return (u8 *)&area_salt_map;
    case AREA_FORTRESS:
        return (u8 *)&area_fortress_map;
    default:
        return (u8 *)&area_hush_map;
    }
}

static u8 *areaCol(u8 a) {
    switch (a) {
    case AREA_VILLAGE:
        return (u8 *)&area_village_col;
    case AREA_FIELDS:
        return (u8 *)&area_fields_col;
    case AREA_FOREST:
        return (u8 *)&area_forest_col;
    case AREA_SHORE:
        return (u8 *)&area_shore_col;
    case AREA_SALT:
        return (u8 *)&area_salt_col;
    case AREA_FORTRESS:
        return (u8 *)&area_fortress_col;
    default:
        return (u8 *)&area_hush_col;
    }
}

static u8 *areaPal(u8 a) {
    switch (a) {
    case AREA_VILLAGE:
        return (u8 *)&area_village_pal;
    case AREA_FIELDS:
        return (u8 *)&area_fields_pal;
    case AREA_FOREST:
        return (u8 *)&area_forest_pal;
    case AREA_SHORE:
        return (u8 *)&area_shore_pal;
    case AREA_SALT:
        return (u8 *)&area_salt_pal;
    case AREA_FORTRESS:
        return (u8 *)&area_fortress_pal;
    default:
        return (u8 *)&area_hush_pal;
    }
}

static u8 *areaAnm(u8 a) {
    switch (a) {
    case AREA_VILLAGE:
        return (u8 *)&area_village_anm;
    case AREA_FIELDS:
        return (u8 *)&area_fields_anm;
    case AREA_FOREST:
        return (u8 *)&area_forest_anm;
    case AREA_SHORE:
        return (u8 *)&area_shore_anm;
    case AREA_SALT:
        return (u8 *)&area_salt_anm;
    case AREA_FORTRESS:
        return (u8 *)&area_fortress_anm;
    default:
        return (u8 *)&area_hush_anm;
    }
}

/* Characters 0..areaAnimTiles-1 of a region's tileset are
 * rewritten from areaAnm() every few frames -- see fieldAnimate.
 * Zero means the region has no moving water. */
static const u8 areaAnimTiles[AREA_COUNT] = {
    4, 4, 8, 8, 0, 4, 4
};

static const u8 areaMusic[AREA_COUNT] = {
    BGM_TOWN, BGM_FIELD, BGM_FOREST, BGM_SHORE, BGM_SALT, BGM_FORTRESS, BGM_HUSH
};

static const u8 areaBackdrop[AREA_COUNT] = {
    0, 0, 1, 2, 3, 4, 5
};

#endif
